window:
    width: 640
    height: 640

physics:
    dt: 0.1
    max_time: 10
    min_x: 0
    min_y: 0
    dist_width: 20
    dist_height: 20

score:
    type: 'BasicReward'
    # params:
    #     hazard_multiplier: 2
    #     death_scale: 0
    #     death_decay: 0.05
    #     death_penalty: 100
    #     time_penalty: 1
    #     missed_multiplier: 10
    #     target_multiplier: 100
    #     wall_penalty: 5
    #     vel_multiplier: 1
    #     min_vel_per: 0.5
    params:
        hazard_multiplier: 2
        death_scale: 0
        death_decay: 0.05
        death_penalty: 100
        time_penalty: 1
        missed_multiplier: 5
        target_multiplier: 50
        wall_penalty: 2
        vel_multiplier: 1
        min_vel_per: 0.2

player:
    birth_model:
        type: Gaussian
        location:
            - 10
            - 5
        scale:
            - 1.5
            - 1.5
        params: None

    dynamics_model:
    #     type: CoordinatedTurn
    #     params:
    #         dt: 0.1
    #     control_model:
    #         type: velocity_turn
    #         max_vel: 5
    #         max_turn_rate: 40
    #     state_constraint:
    #         type: velocity
    #         max_vels:
    #             - 10
    #             - 10
    #         min_vels:
    #             - 0
    #             - 0

        type: DoubleIntegrator
        control_model:
            type: velocity
            max_vel_x: 5
            max_vel_y: 5
        state_constraint:
            type: velocity
            max_vels:
                - 5
                - 5
            min_vels:
                - -5
                - -5

    shape_model:
        type: 'rect'
        width: 1
        height: 1
        color:
            - 0
            - 0
            - 255

    collision_model:
        width: 1
        height: 1

    capabilities:
        - 'radar'
        - 'lidar'


obstacles:
    -
      loc_x: 15
      loc_y: 16
      width: 3
      height: 3
      shape_type: 'rect'
      shape_color:
          - 0
          - 0
          - 0
      collision_width: 3
      collision_height: 3

    -
      loc_x: 17.5
      loc_y: 7.5
      width: 5
      height: 0.5
      shape_type: 'rect'
      shape_color:
          - 0
          - 0
          - 0
      collision_width: 5
      collision_height: 0.5

    -
      loc_x: 5
      loc_y: 15
      width: 1.5
      height: 5
      shape_type: 'rect'
      shape_color:
          - 0
          - 0
          - 0
      collision_width: 1.5
      collision_height: 5
    -
      loc_x: 5
      loc_y: 2.5
      width: 1.5
      height: 5
      shape_type: 'rect'
      shape_color:
          - 0
          - 0
          - 0
      collision_width: 1.5
      collision_height: 5

    -
      loc_x: 10
      loc_y: 12.5
      width: 5
      height: 1
      shape_type: 'rect'
      shape_color:
          - 0
          - 0
          - 0
      collision_width: 5
      collision_height: 1

targets:
    -
      priority: 2
      loc_x: 2.5
      loc_y: 15
      width: 1.5
      height: 1.5
      shape_type: 'rect'
      shape_color:
          - 0
          - 255
          - 0
      collision_width: 1.5
      collision_height: 1.5

      capabilities:
          - 'radar'

    -
      priority: 1
      loc_x: 10
      loc_y: 15
      width: 1
      height: 1
      shape_type: 'rect'
      shape_color:
          - 0
          - 255
          - 0
      collision_width: 1
      collision_height: 1

      capabilities:
          - 'radar'
          - 'lidar'

# hazards:
#     -
#       loc_x: 15
#       loc_y: 17
#       width: 20
#       height: 5
#       shape_type: 'rect'
#       shape_color:
#           - 255
#           - 215
#           - 0
#       collision_width: 20
#       collision_height: 5
#       prob_of_death: 0.05

#     -
#       loc_x: 10
#       loc_y: 38
#       width: 3
#       height: 6
#       shape_type: 'rect'
#       shape_color:
#           - 255
#           - 215
#           - 0
#       collision_width: 3
#       collision_height: 6
#       prob_of_death: 0.1
