window:
    width: 640
    height: 480

physics:
    dt: 0.1
    max_time: 100
    origin_x: 0
    origin_y: 0
    dist_per_pix: 10

player:
    birth_model:
        type: Gaussian
        location:
            - 200
            - 100
        scale:
            - 2
            - 2
        params: None

    dynamics_model: TODO implement this

    shape_model:
        type: 'rect'
        width: 2
        height: 2
        color:
            - 0
            - 0
            - 255

    collision_model:
        width: 10
        height: 10

obstacles:
    -
      loc_x: 20
      loc_y: 20
      width: 3
      height: 3
      shape_type: 'rect'
      shape_color:
          - 0
          - 0
          - 0
      collision_width: 6
      collision_height: 6
    -
      loc_x: 200
      loc_y: 80
      width: 6
      height: 6
      shape_type: 'rect'
      shape_color:
          - 0
          - 0
          - 0
      collision_width: 6
      collision_height: 6
